discord:
  token: "DEIN_DISCORD_BOT_TOKEN_HIER"
  guild-id: "DEINE_DISCORD_GUILD_ID_HIER"
  voice-channel-id: "DEINE_DISCORD_VOICE_CHANNEL_ID_HIER"
  linked-players:

bedrock-challenge:
  spawn-locations:
    - "void,0.5,100,0.5"
    - "void,100.5,100,0.5"
    # Du kannst hier so viele Koordinaten eintragen, wie du Spieler hast

challenges:
  allItems:
    collectedCount: 2
    currentTarget: GOLD_INGOT
    collectedItemsList:
      - DIAMOND
      - DIRT

monsterbattle:
  # Der Punkt, an dem die Spieler in der Arena stehen
  spawn: "100.5, 64.0, 100.5"

