name: Discord Notify

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: fjogeleit/http-request-action@v1

      - name: Read version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Send Discord Webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          method: POST
          contentType: 'application/json'
          data: |
            {
              "content": "<@&1486792059389083678>",
              "username": "Challenge Plugin",
              "avatar_url": "https://smp-modcraft.de/challenges.png",
              "embeds": [
                {
                  "title": "Challenges Updates",
                  "description": "**New update available!**\nVersion ${{ env.VERSION }} is now available for download.\n\n**Changelog:**\n${{ github.event.head_commit.message }}",
                  "color": 5763719,
                  "footer": {
                    "text": "Challenges • https://smp-modcraft.de/plugins/challenge"
                  },
                  "timestamp": "${{ github.event.head_commit.timestamp || github.event.created_at }}"
                }
              ]
            }