name: Discord Notify

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, closed]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          method: POST
          contentType: 'application/json'
          body: |
            {
              "content": "📢 Repo Update!\nBranch: ${{ github.ref }}\nUser: ${{ github.actor }}\nEvent: ${{ github.event_name }}",
              "username": "GitHub Bot",
              "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
            }
