name: Discord Notify

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, closed]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          method: POST
          contentType: 'application/json'
          data: |
            {
              "username": "GitHub Bot",
              "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "embeds": [
                {
                  "title": "GitHub Update!",
                  "description": "Branch: ${{ github.ref }}\nUser: ${{ github.actor }}\nEvent: ${{ github.event_name }}",
                  "color": 5814783,
                  "timestamp": "${{ github.event.head_commit.timestamp || github.event.created_at }}"
                }
              ]
            }